[2023-01-26T16:18:02.913+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Submit_data_to_kafka manual__2023-01-23T22:03:04.495188+00:00 [queued]>
[2023-01-26T16:18:02.924+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Submit_data_to_kafka manual__2023-01-23T22:03:04.495188+00:00 [queued]>
[2023-01-26T16:18:02.924+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T16:18:02.924+0000] {taskinstance.py:1284} INFO - Starting attempt 97 of 101
[2023-01-26T16:18:02.924+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-26T16:18:02.937+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Submit_data_to_kafka> on 2023-01-23 22:03:04.495188+00:00
[2023-01-26T16:18:02.941+0000] {standard_task_runner.py:55} INFO - Started process 2972 to run task
[2023-01-26T16:18:02.943+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Submit_data_to_kafka', 'manual__2023-01-23T22:03:04.495188+00:00', '--job-id', '1032', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpjid59v2w']
[2023-01-26T16:18:02.943+0000] {standard_task_runner.py:83} INFO - Job 1032: Subtask Submit_data_to_kafka
[2023-01-26T16:18:02.999+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Submit_data_to_kafka manual__2023-01-23T22:03:04.495188+00:00 [running]> on host 7f54167b3933
[2023-01-26T16:18:03.066+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Submit_data_to_kafka
AIRFLOW_CTX_EXECUTION_DATE=2023-01-23T22:03:04.495188+00:00
AIRFLOW_CTX_TRY_NUMBER=97
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-23T22:03:04.495188+00:00
[2023-01-26T16:18:03.068+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2023-01-26T16:18:03.068+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-26T16:18:03.068+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]> returned error 111. Disconnecting.
[2023-01-26T16:18:03.069+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-26T16:18:03.118+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: connecting to 172.17.0.1:9092 [('172.17.0.1', 9092) IPv4]
[2023-01-26T16:18:03.118+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]> returned error 111. Disconnecting.
[2023-01-26T16:18:03.118+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.17.0.1:9092 <connecting> [IPv4 ('172.17.0.1', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-26T16:18:03.119+0000] {producer_dag.py:21} ERROR - Hubo un error al conectarse a kafka: NoBrokersAvailable
[2023-01-26T16:18:04.068+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/producer_dag.py", line 49, in runKafkaProducer
    producer.send('myTopic', data)
UnboundLocalError: local variable 'producer' referenced before assignment
[2023-01-26T16:18:04.083+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Streaming_pipeline_meli, task_id=Submit_data_to_kafka, execution_date=20230123T220304, start_date=20230126T161802, end_date=20230126T161804
[2023-01-26T16:18:04.106+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1032 for task Submit_data_to_kafka (local variable 'producer' referenced before assignment; 2972)
[2023-01-26T16:18:04.119+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-26T16:18:04.139+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
