[2023-01-30T17:20:59.814+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T18:49:27.597637+00:00 [queued]>
[2023-01-30T17:20:59.825+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T18:49:27.597637+00:00 [queued]>
[2023-01-30T17:20:59.825+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T17:20:59.825+0000] {taskinstance.py:1284} INFO - Starting attempt 9 of 14
[2023-01-30T17:20:59.825+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-30T17:20:59.841+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Status_info_mongodb> on 2023-01-27 18:49:27.597637+00:00
[2023-01-30T17:20:59.845+0000] {standard_task_runner.py:55} INFO - Started process 6507 to run task
[2023-01-30T17:20:59.848+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Status_info_mongodb', 'manual__2023-01-27T18:49:27.597637+00:00', '--job-id', '1221', '--raw', '--subdir', 'DAGS_FOLDER/streamPipeline.py', '--cfg-path', '/tmp/tmpi90qq4dp']
[2023-01-30T17:20:59.848+0000] {standard_task_runner.py:83} INFO - Job 1221: Subtask Status_info_mongodb
[2023-01-30T17:20:59.911+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Status_info_mongodb manual__2023-01-27T18:49:27.597637+00:00 [running]> on host 15c99fd3082a
[2023-01-30T17:20:59.976+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Status_info_mongodb
AIRFLOW_CTX_EXECUTION_DATE=2023-01-27T18:49:27.597637+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-27T18:49:27.597637+00:00
[2023-01-30T17:21:30.056+0000] {mongoStatus.py:16} ERROR - Error al conectar a mongoDB: 172.20.0.8:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 63d7fc7bd23a8bb73c744e3d, topology_type: Single, servers: [<ServerDescription ('172.20.0.8', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('172.20.0.8:27017: [Errno 111] Connection refused')>]>
[2023-01-30T17:21:30.056+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-30T17:21:30.064+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Streaming_pipeline_meli, task_id=Status_info_mongodb, execution_date=20230127T184927, start_date=20230130T172126, end_date=20230130T172130
[2023-01-30T17:21:30.083+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-30T17:21:30.098+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
