[2023-01-31T20:03:33.529+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T20:03:33.539+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T20:03:33.540+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T20:03:33.540+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 9
[2023-01-31T20:03:33.540+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T20:03:33.556+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Uploading_data_to_aws_rds> on 2023-01-31 16:01:06.868325+00:00
[2023-01-31T20:03:33.560+0000] {standard_task_runner.py:55} INFO - Started process 19689 to run task
[2023-01-31T20:03:33.563+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Uploading_data_to_aws_rds', 'manual__2023-01-31T16:01:06.868325+00:00', '--job-id', '1317', '--raw', '--subdir', 'DAGS_FOLDER/streamPipeline.py', '--cfg-path', '/tmp/tmpt8lgt6ix']
[2023-01-31T20:03:33.563+0000] {standard_task_runner.py:83} INFO - Job 1317: Subtask Uploading_data_to_aws_rds
[2023-01-31T20:03:33.620+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [running]> on host 15c99fd3082a
[2023-01-31T20:03:33.693+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Uploading_data_to_aws_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T16:01:06.868325+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T16:01:06.868325+00:00
[2023-01-31T20:03:33.693+0000] {loadDataToRds.py:16} ERROR - Ocurrio un error al subir los datos a aws rds: Expected bytes or unicode string, got dict instead
[2023-01-31T20:03:33.693+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-01-31T20:03:33.703+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=Streaming_pipeline_meli, task_id=Uploading_data_to_aws_rds, execution_date=20230131T160106, start_date=20230131T200333, end_date=20230131T200333
[2023-01-31T20:03:33.735+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-01-31T20:03:33.750+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
