[2023-01-31T21:15:26.449+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T21:15:26.459+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [queued]>
[2023-01-31T21:15:26.459+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T21:15:26.459+0000] {taskinstance.py:1284} INFO - Starting attempt 34 of 39
[2023-01-31T21:15:26.459+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-31T21:15:26.472+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): Uploading_data_to_aws_rds> on 2023-01-31 16:01:06.868325+00:00
[2023-01-31T21:15:26.475+0000] {standard_task_runner.py:55} INFO - Started process 26668 to run task
[2023-01-31T21:15:26.478+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Streaming_pipeline_meli', 'Uploading_data_to_aws_rds', 'manual__2023-01-31T16:01:06.868325+00:00', '--job-id', '1351', '--raw', '--subdir', 'DAGS_FOLDER/streamPipeline.py', '--cfg-path', '/tmp/tmpnyppy0ms']
[2023-01-31T21:15:26.480+0000] {standard_task_runner.py:83} INFO - Job 1351: Subtask Uploading_data_to_aws_rds
[2023-01-31T21:15:26.530+0000] {task_command.py:389} INFO - Running <TaskInstance: Streaming_pipeline_meli.Uploading_data_to_aws_rds manual__2023-01-31T16:01:06.868325+00:00 [running]> on host 15c99fd3082a
[2023-01-31T21:15:26.592+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Streaming_pipeline_meli
AIRFLOW_CTX_TASK_ID=Uploading_data_to_aws_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-01-31T16:01:06.868325+00:00
AIRFLOW_CTX_TRY_NUMBER=34
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-31T16:01:06.868325+00:00
[2023-01-31T21:15:26.593+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: uploadData() missing 1 required positional argument: 'data'
[2023-01-31T21:15:26.599+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Streaming_pipeline_meli, task_id=Uploading_data_to_aws_rds, execution_date=20230131T160106, start_date=20230131T211526, end_date=20230131T211526
[2023-01-31T21:15:26.609+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1351 for task Uploading_data_to_aws_rds (uploadData() missing 1 required positional argument: 'data'; 26668)
[2023-01-31T21:15:26.650+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-31T21:15:26.665+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
