[2023-01-21T03:52:55.448+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-21T03:52:55.457+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [queued]>
[2023-01-21T03:52:55.457+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:52:55.457+0000] {taskinstance.py:1284} INFO - Starting attempt 23 of 23
[2023-01-21T03:52:55.457+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T03:52:55.469+0000] {taskinstance.py:1304} INFO - Executing <Task(SparkSubmitOperator): consumer_data_of_topic> on 2023-01-19 22:08:17.592063+00:00
[2023-01-21T03:52:55.473+0000] {standard_task_runner.py:55} INFO - Started process 5634 to run task
[2023-01-21T03:52:55.475+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'consumer_data_of_topic', 'manual__2023-01-19T22:08:17.592063+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpromgzi1q']
[2023-01-21T03:52:55.476+0000] {standard_task_runner.py:83} INFO - Job 297: Subtask consumer_data_of_topic
[2023-01-21T03:52:55.524+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.consumer_data_of_topic manual__2023-01-19T22:08:17.592063+00:00 [running]> on host 3cc77177a430
[2023-01-21T03:52:55.580+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=consumer_data_of_topic
AIRFLOW_CTX_EXECUTION_DATE=2023-01-19T22:08:17.592063+00:00
AIRFLOW_CTX_TRY_NUMBER=23
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-19T22:08:17.592063+00:00
[2023-01-21T03:52:55.587+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-01-21T03:52:55.588+0000] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py
[2023-01-21T03:52:55.689+0000] {spark_submit.py:495} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-01-21T03:52:57.584+0000] {spark_submit.py:495} INFO - python3: can't open file '/home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py': [Errno 2] No such file or directory
[2023-01-21T03:52:57.594+0000] {spark_submit.py:495} INFO - 23/01/21 03:52:57 INFO ShutdownHookManager: Shutdown hook called
[2023-01-21T03:52:57.596+0000] {spark_submit.py:495} INFO - 23/01/21 03:52:57 INFO ShutdownHookManager: Deleting directory /tmp/spark-1baeea2a-df8a-4f80-aca3-7722f20e49ef
[2023-01-21T03:52:57.634+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 427, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py. Error code is: 2.
[2023-01-21T03:52:57.637+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=Kafka_consumer, task_id=consumer_data_of_topic, execution_date=20230119T220817, start_date=20230121T035255, end_date=20230121T035257
[2023-01-21T03:52:57.649+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 297 for task consumer_data_of_topic (Cannot execute: spark-submit --master spark://tomi-H310:7077 --name arrow-spark --queue root.default /home/tomi/streamingPipelineMercadoLibre/docker_***/dags/pi.py. Error code is: 2.; 5634)
[2023-01-21T03:52:57.695+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-21T03:52:57.724+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
