[2023-01-18T22:16:56.810+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T22:16:56.818+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [queued]>
[2023-01-18T22:16:56.818+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:16:56.818+0000] {taskinstance.py:1284} INFO - Starting attempt 18 of 23
[2023-01-18T22:16:56.818+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-18T22:16:56.831+0000] {taskinstance.py:1304} INFO - Executing <Task(ProduceToTopicOperator): producer> on 2023-01-18 21:35:11.718856+00:00
[2023-01-18T22:16:56.840+0000] {standard_task_runner.py:55} INFO - Started process 3909 to run task
[2023-01-18T22:16:56.845+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Kafka_consumer', 'producer', 'manual__2023-01-18T21:35:11.718856+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/producer_dag.py', '--cfg-path', '/tmp/tmpf7e7_6sf']
[2023-01-18T22:16:56.845+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask producer
[2023-01-18T22:16:56.901+0000] {task_command.py:389} INFO - Running <TaskInstance: Kafka_consumer.producer manual__2023-01-18T21:35:11.718856+00:00 [running]> on host f2df97c6ee42
[2023-01-18T22:16:56.962+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Kafka_consumer
AIRFLOW_CTX_TASK_ID=producer
AIRFLOW_CTX_EXECUTION_DATE=2023-01-18T21:35:11.718856+00:00
AIRFLOW_CTX_TRY_NUMBER=18
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-18T21:35:11.718856+00:00
[2023-01-18T22:16:56.978+0000] {producer.py:55} INFO - Producer <cimpl.Producer object at 0x7f55204f45d0>
[2023-01-18T22:16:56.980+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: connecting to 172.22.0.7:9092 [('172.22.0.7', 9092) IPv4]
[2023-01-18T22:16:56.980+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2023-01-18T22:16:56.981+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]> returned error 111. Disconnecting.
[2023-01-18T22:16:56.981+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T22:16:57.030+0000] {conn.py:381} INFO - <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: connecting to 172.22.0.7:9092 [('172.22.0.7', 9092) IPv4]
[2023-01-18T22:16:57.030+0000] {conn.py:419} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]> returned error 111. Disconnecting.
[2023-01-18T22:16:57.030+0000] {conn.py:919} INFO - <BrokerConnection node_id=bootstrap-0 host=172.22.0.7:9092 <connecting> [IPv4 ('172.22.0.7', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2023-01-18T22:16:57.031+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow_provider_kafka/operators/produce_to_topic.py", line 114, in execute
    for k, v in producer_callable():
  File "/opt/airflow/dags/producer_dag.py", line 12, in runKafkaProducer
    value_serializer=lambda x: json.dumps(x).encode('utf-8'))
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2023-01-18T22:16:57.047+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=Kafka_consumer, task_id=producer, execution_date=20230118T213511, start_date=20230118T221656, end_date=20230118T221657
[2023-01-18T22:16:57.057+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 86 for task producer (NoBrokersAvailable; 3909)
[2023-01-18T22:16:57.096+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-18T22:16:57.113+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
